import { ModuleOnline } from "@/components/dashboard/ModuleOnline";

export default function InsightsPage() {
  return (
    <ModuleOnline
      title="AI Insights"
      desc="Natural-language summaries of what customers love and hate — generated by the neural engine in the next phase."
    />
  );
}
